version: 2
jobs:
  build-and-test:
    working_directory: /ITKCSIROTomo-build
    docker:
      - image: insighttoolkit/module-ci:v4.13
    steps:
      - add_ssh_keys:
          fingerprints:
            - "cf:34:a3:8d:e0:f6:6d:3f:9b:75:f1:bb:60:ee:59:c1"
      - checkout:
          path: /ITKCSIROTomo
      - run:
          name: Fetch CTest driver script
          command: |
            curl -L https://raw.githubusercontent.com/InsightSoftwareConsortium/ITK/dashboard/itk_common.cmake -O
      - run:
          name: Configure CTest script
          command: |
            SHASNIP=$(echo $CIRCLE_SHA1 | cut -c1-7)
            cat > dashboard.cmake << EOF
            set(CTEST_SITE "CircleCI")
            set(CTEST_BUILD_NAME "External-ITKCSIROTomo-${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}-${SHASNIP}")
            set(CTEST_BUILD_CONFIGURATION "MinSizeRel")
            set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
            set(CTEST_BUILD_FLAGS: "-j5")
            set(CTEST_SOURCE_DIRECTORY /ITKCSIROTomo)
            set(CTEST_BINARY_DIRECTORY /ITKCSIROTomo-build)
            set(dashboard_model Experimental)
            set(dashboard_no_clean 1)
            set(dashboard_cache "
            ITK_DIR:PATH=/ITK-build
            BUILD_TESTING:BOOL=ON
            ")
            include(\${CTEST_SCRIPT_DIRECTORY}/itk_common.cmake)
            EOF
      - run:
          name: Build and Test
          no_output_timeout: 1.0h
          command: |
            ctest -j 2 -VV -S dashboard.cmake
  package:
    working_directory: ~/ITKCSIROTo
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "cf:34:a3:8d:e0:f6:6d:3f:9b:75:f1:bb:60:ee:59:c1"
      - checkout
      - run:
          name: Fetch build script
          command: |
            curl -L https://rawgit.com/InsightSoftwareConsortium/ITKPythonPackage/release-4.13/scripts/dockcross-manylinux-download-cache-and-build-module-wheels.sh -O
            chmod u+x dockcross-manylinux-download-cache-and-build-module-wheels.sh
      - run:
          name: Build Python packages
          no_output_timeout: 1.0h
          command: |
            export ITK_PACKAGE_VERSION=v4.13.0
            ./dockcross-manylinux-download-cache-and-build-module-wheels.sh
      - store_artifacts:
          path: dist
          destination: dist

workflows:
    version: 2
    build-test-package:
      jobs:
#        - build-and-test
        - package
